services:
  next_frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: frontend
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "3030:3030"
    working_dir: /app