
services:
  minio:
    image: minio/minio
    container_name: minio
    command: server /data
    ports:
      - "9000:9000"
    environment:
      MINIO_ACCESS_KEY: minio_test
      MINIO_SECRET_KEY: password123
    volumes:
      - /opt/minio/data:/data
    restart: on-failure
