services:
  postgres:
    image: postgres:17-alpine
    container_name: postgres
    restart: unless-stopped
    network_mode: host
    env_file:
      - .env
    volumes:
      - /opt/postgresql/data:/var/lib/postgresql/data