export const fileUrlPrefix = 'files'
export const bucketUrlPrefix = 'buckets'
export const moveFileUrlPrefix = 'files/move'
export const renameFileUrlPrefix = 'files/rename'
export const authUrlPrefix = 'auth'
